### ISSUE TITLE
No unicode?

### ISSUE THREAD

**Issue by gjedeer** [podhmo/python-semver#1]
Nice job on this package!

Is unicode unsupported by design or is it a bug? When the list of versions contains an unicode string, an "Invalid version" ValueError is raised here:

https://github.com/podhmo/python-semver/blob/master/semver/__init__.py#L288

**Comment by podhmo** [comment]
I have no-memory about it. But it seems bug for me (now). Maybe, this package developed for python3.x, that is why the unicode type is not support seriously.

anyway, this is bug, so I will try to fix this behaviour.

**Comment by podhmo** [comment]
same as #13 ?
