### ISSUE TITLE
[question] Support for Python 2

### ISSUE THREAD

**Issue by memsharded** [podhmo/python-semver#13]
I see https://github.com/podhmo/python-semver/commit/b42e9896e391e086b773fc621b23fa299d16b874 has removed Python 2, though the code is still compatible, and it works. What are the plans regarding this? Thank you!

**Comment by podhmo** [comment]
Ah, yes, maybe working correctly in **non-multibyte** input.
Current implementation is not treating multibyte strings, in python2.x.
