### ISSUE TITLE
Loose parsing of 4-digit version does not match node.js semver.coerce()

### ISSUE THREAD

**Issue by puetzk** [podhmo/python-semver#15]
First reported at conan-io/conan#3627

I have some packages that use 4-field version numbers, because they must provide win32 version resources and manifests, and those don't allow the 4th field to be omitted. However, we don't really use the last field (because it has no semver-defined meaning), so it's just 0 (or occasionally a build iteration that doesn't need to participate in comparisons any more than the `+build` field would).

In struct mode, your package rejects these (correctly). However, in loose mode, the python semver package seems to take the first, second, and *last* of the dotted fields for major/minor/patch in loose mode, ignoring the 3rd (patch) field where the difference is. This leads to it making no distinction between 4.1.1.0, 4.1.2.0, 4.1.3.0, etc; they all parse to <SemVer 4.1.0>.

```python
>>> from semver import make_semver, max_satisfying

>>> make_semver('4.1.3.0', loose=False)
ValueError: Invalid Version: 4.1.3.0

>>> make_semver('4.1.3.0', loose=True)
<SemVer 4.1.0 >

>>> max_satisfying(['3.1.1','4.1.1.0', '4.1.2.0','4.1.3.0'], '^4.1',loose=True)
'4.1.1.0'
>>> max_satisfying([''3.1.1', 4.1.2.0', '4.1.1.0','4.1.3.0'], '^4.1',loose=True)
'4.1.2.0'
```

This was an unexpected choice, and it does not agree with the behavior of the node.js semver package it's nominally a clone of: https://repl.it/repls/CompetentImpossibleCookie

```js
const semver = require('semver');

console.log('4.1.3.0 -> ' + semver.coerce('4.1.3.0'))
console.log('4.1.3.1 -> ' + semver.coerce('4.1.3.0'))
console.log(semver.maxSatisfying([semver.coerce('4.1.0.0'),semver.coerce('4.1.1.0'),semver.coerce('4.1.3.0')], '^4.1'))
```

Where coercing 4.1.3.0 yields 4.1.3, as I thought it would

```
4.1.3.0 -> 4.1.3
4.1.3.1 -> 4.1.3
SemVer {
  loose: undefined,
  raw: '4.1.3',
  major: 4,
  minor: 1,
  patch: 3,
  prerelease: [],
  build: [],
  version: '4.1.3' }
```

This leads to some further complications (non-determinism) in conan, as max_satisfying seems to break ties (e.g. this bug, or ignored +build fields, or whatever) toward the string listed first in the input, and conan doesn't seem to always provide a deterministic sort of of its input. But node.js's semver.maxSatisfying seems to do the same (choose the first-among-equals), at least there you're consistent with the expected behavior, and the nondeterminism seems like conan's issue.

**Comment by podhmo** [comment]
supported by 0.4.0

**Comment by puetzk** [comment]
Ok, I was expecting the fix to be using the 3rd field and ignoring the 4th, like node does. You've definitely done that, but actually supporting micro versions is even better.

```
> make_semver('4.1.3.0', loose=True).__dict__
{'loose': True, 'raw': '4.1.3.0', 'micro_versions': [0], 'major': 4, 'minor': 1, 'patch': 3, 'prerelease': [], 'version': '4.1.3.0'}
```

However, this seems to interact weirdly with +build or -pre suffixes, with either of those, along with the micro-versions, getting sucked into prerelease...

```
> make_semver('4.1.3.0+jenkins', loose=True).__dict__
{'loose': True, 'raw': '4.1.3.0+jenkins', 'micro_versions': [], 'major': 4, 'minor': 1, 'patch': 3, 'prerelease': ['0+jenkins'], 'version': '4.1.3-0+jenkins'}

> make_semver('4.1.3.0-pre', loose=True).__dict__
{'loose': True, 'raw': '4.1.3.0-pre', 'micro_versions': [], 'major': 4, 'minor': 1, 'patch': 3, 'prerelease': ['0-pre'], 'version': '4.1.3-0-pre'}
```

I would have thought: 
```
> make_semver('4.1.3.0+jenkins', loose=True).__dict__
{'loose': True, 'raw': '4.1.3.0+jenkins', 'micro_versions': [0], 'major': 4, 'minor': 1, 'patch': 3, 'build': ['jenkins'], 'version': '4.1.3.0'}

> make_semver('4.1.3.0-pre', loose=True).__dict__
{'loose': True, 'raw': '4.1.3.0-pre', 'micro_versions': [0], 'major': 4, 'minor': 1, 'patch': 3, 'prerelease': ['pre'], 'version': '4.1.3.0-pre'}
```

Parsing of +build or -pre still seems fine if you don't have 4 numeric fields:
```
> make_semver('4.1.3+jenkins', loose=True).__dict__
{'loose': True, 'raw': '4.1.3+jenkins', 'micro_versions': [], 'major': 4, 'minor': 1, 'patch': 3, 'prerelease': [], 'build': ['jenkins'], 'version': '4.1.3'}
> make_semver('4.1.3-pre', loose=True).__dict__
{'loose': True, 'raw': '4.1.3-pre', 'micro_versions': [], 'major': 4, 'minor': 1, 'patch': 3, 'prerelease': ['pre'], 'build': [], 'version': '4.1.3-pre'}
```

**Comment by podhmo** [comment]
ah,ok.I'll try to fix

**Comment by podhmo** [comment]
fixed. (0.4.2)
