### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by blink1073** [podhmo/python-semver#2]
Hi @podhmo, thank you for this library!  

Would you be willing to add a BSD-compatible license to this library, either as a standalone file or in `setup.py`?  I am more than happy to submit a PR. 

Our library, [JupyterLab](https://github.com/jupyterlab/jupyterlab), uses "License :: OSI Approved :: BSD License" and we would like to vendor the main source file of this repo rather than add a package dependency, since npm semver is not generally applicable to the user's environment when they are using JupyterLab, but is an implementation detail of how we serve pre-built JavaScript files.

**Comment by podhmo** [comment]
oh, sorry. Basically, I thought my all repositories are MIT License.

**Comment by podhmo** [comment]
I committed.
https://github.com/podhmo/python-semver/commit/f0392c5567717ad001c058d80fa09887e482ad62

**Comment by blink1073** [comment]
Great, thank you!
