### ISSUE TITLE
max_satisfying doesn't work with byte-strings on Python3

### ISSUE THREAD

**Issue by jeverling** [podhmo/python-semver#26]
Using Python 3, if you pass byte-strings to `max_satisfying`, it returns `None`.

The reason is a `TypeError: cannot use a string pattern on a bytes-like object` exception in [semver#L740](https://github.com/podhmo/python-semver/blob/e60ed50e438c5c58c4298a44c9204a38f9d766b6/semver/__init__.py#L740), however this exception is masked by a bare `except` statement in [semver#L1079](https://github.com/podhmo/python-semver/blob/e60ed50e438c5c58c4298a44c9204a38f9d766b6/semver/__init__.py#L1079), that leads to `max_satisfying` returning `None`.

I think it would be good to document that byte-strings need to be decoded before they can be passed to *semver*.
Alternatively, the library could try to decode byte-strings before using them, which should be reasonably easy because semvers are supposed to be ascii only.

**Comment by podhmo** [comment]
oh, returning none is bad behavior. at least, should be error is raised

**Comment by podhmo** [comment]
Honestly, I don't like treating bytes type as string. But, so, semver format is not including multi bytes char, normaly.

**Comment by jeverling** [comment]
I think it's enough to raise the error, it is then up to the user to make sure to pass strings not bytes. But at the moment it's not easy to see why it doesn't work.

**Comment by podhmo** [comment]
0.6.0 is released

```python
from semver import max_satisfying

print(max_satisfying([b"1.0.0"], "1.0.0"))
# semver.InvalidTypeIncluded: must be str, but b'1.0.0'
```

**Comment by jeverling** [comment]
Thank you for the quick fix!
