### ISSUE TITLE
Handling of version numbers with more than three digits

### ISSUE THREAD

**Issue by jasal82** [podhmo/python-semver#34]
Would it be possible to apply numeric ordering for version numbers that use more than three digits? We are indirect users of python-semver via the Conan C++ package manager which uses python-semver to resolve and order package versions. There we have some legacy components that use four-digit version numbers. The fourth digit is currently not significant and completely ignored in the ordering. The order is not even consistent between different systems, so on some machines e.g. 3.8.0.1 is considered newer than 3.8.0.0 whereas another machine orders it the other way around.

**Comment by podhmo** [comment]
Is it the same situation? https://github.com/podhmo/python-semver/issues/15

**Comment by jasal82** [comment]
No, that issue says that in a four-digit version number A.B.C.D python-semver uses A.B.D for comparison. What we observe is that sometimes A.B.C.(D+1) > A.B.C.D and sometimes A.B.C.(D+1) < A.B.C.D.

**Comment by podhmo** [comment]
Ah, OK.

https://gist.github.com/podhmo/917440085dbb77162837eb028615a2b8

**Comment by podhmo** [comment]
https://github.com/podhmo/python-semver/blob/a59531ac9916aa594449733379b7e0228ce769f2/semver/__init__.py#L394

This line's evaluation does not support micro.version.

**Comment by podhmo** [comment]
Anyway, it is OK that `1.1.1.1 < 1.1.1.2`, but what is the correct result for the following example?

- `1.1.1 vs 1.1.1.1`
- `1.1.1-pre1 vs 1.1.1.1`

**Comment by podhmo** [comment]
:memo: The first example is the same as `1.1 vs 1.1.1`.

**Comment by podhmo** [comment]
And, `1.1` is treated as `1.1.0` isn't it? So, `1.1.1-pre1 < 1.1.1` then, `1.1.1-pre < 1.1.1.1` ?

**Comment by podhmo** [comment]
The results sorting in ascending order is `[1.1, 1.1.1-pre1, 1.1.1, 1.1.1.1]` ?

**Comment by podhmo** [comment]
https://gist.github.com/podhmo/2011ef7c8b64ec1bc086c7e43beeb98c

**Comment by podhmo** [comment]
0.8.0 is released

**Comment by podhmo** [comment]
Closing this issue, but feel free to reopen or comments if somehow wrong.
