### ISSUE TITLE
Pre-releases having precedence over releases

### ISSUE THREAD

**Issue by memsharded** [podhmo/python-semver#5]
It seems that pre-releases have precedence over releases, i.e.:

```python
result = satisfying(["1.1.1", "1.1.1-11", "1.1.1-111", "1.1.1-21"], "", output)
self.assertEqual(result, "1.1.1-111")  # Wrong, should be 1.1.1
```
where ``satisfying`` is just a small wrapper of ``max_satisfying`` to convert from the strings to ``SemVer(v, loose=True)``

I have had a look to the code, but couldn't figure out a fix. Many thanks!

**Comment by podhmo** [comment]
hmm.

**Comment by podhmo** [comment]
memo
https://gist.github.com/podhmo/3a847bf5f6f97a10f8241fe697d571f0

**Comment by memsharded** [comment]
Yes, you are right, it happens to be part of my expression, I am sorry.

But when I fix it, my tests fail because of this:

```python
wanted = "1.2" 
cands =  ["1.1.1", "1.2", "1.1.1-111", "1.1.1-21"]
result = max_satisfying(cands, "<=1.2", loose=True)
assert wanted == result, "result is %s" % result
```

I can't see in the semver specification the reason of this result. Am I missing something?
Many thanks, and thanks again for this useful library!

**Comment by podhmo** [comment]
in node.js's semver `1.2` is invalid version expression. (implementation is changed)

current node's regexp
```
/^[v=\s]*([0-9]+)\.([0-9]+)\.([0-9]+)(?:-?((?:[0-9]+|\d*[a-zA-Z-][a-zA-Z0-9-]*)(?:\.(?:[0-9]+|\d*[a-zA-Z-][a-zA-Z0-9-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/
```

python's one
```
re.compile('^[v=\\s]*([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-?((?:[0-9]+|\\d*[a-zA-Z-][a-zA-Z0-9-]*)(?:\\.(?:[0-9]+|\\d*[a-zA-Z-][a-zA-Z0-9-]*))*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$')
```

## detail

```js
const semver = require('semver');
wanted = "1.2";
cands =  ["1.1.1", "1.2", "1.1.1-111", "1.1.1-21"];
console.log(semver.maxSatisfying(cands, "<=1.2", true))

// TypeError: Invalid Version: 1.2
```

```js
const semver = require('semver');
wanted = "1.2";
cands =  ["1.1.1", "1.2.0", "1.1.1-111", "1.1.1-21"];
console.log(semver.maxSatisfying(cands, "<=1.2", true)) // 1.2.0
```

**Comment by podhmo** [comment]
but, python's version is broken.

```python
from semver import max_satisfying
wanted = "1.2"
cands = ["1.1.1", "1.2.0", "1.1.1-111", "1.1.1-21"]
result = max_satisfying(cands, "<=1.2", loose=True)
print(result)  # 1.1.1
```

**Comment by podhmo** [comment]
fixed, and releasing ver 0.2.0, as soon as.

**Comment by podhmo** [comment]
released

**Comment by memsharded** [comment]
I am testing my codebase with 0.2.0, this issue has been fixed, but now, other tests that were passing for me now are failing, like if the behavior for other cases has been changed too. I am investigating, will report.

**Comment by podhmo** [comment]
thx!

**Comment by podhmo** [comment]
I'm closing this issue.  If new bug is found, could you create another issue.

**Comment by memsharded** [comment]
I am fine with this fix, the tests that were failing where because of some workarounds I had in place, but the new behavior seems correct, not only for the pre-release issue, but also other corner cases have improved too. Thanks again!
